# Generated by Django 4.2.4 on 2023-10-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='put_date',
            new_name='pub_date',
        ),
    ]
