# Generated by Django 4.2.6 on 2023-11-01 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0003_book_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Age must be at least 1.'), django.core.validators.MaxValueValidator(100, message='Age cannot exceed 100.')])),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='book_pictures/'),
        ),
    ]
