# Generated by Django 4.2.6 on 2023-11-01 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0004_writer_alter_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realsite.writer'),
        ),
    ]
