# Generated by Django 4.2.6 on 2023-11-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0005_alter_book_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='name',
            field=models.CharField(default='DefaultName', max_length=100),
        ),
    ]
