# Generated by Django 4.2.6 on 2023-11-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0006_writer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='name',
        ),
        migrations.AddField(
            model_name='writer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='writer_images/'),
        ),
    ]
