# Generated by Django 4.2.7 on 2023-11-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0007_remove_writer_name_writer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='creatorname',
            field=models.CharField(default='Name', max_length=200),
        ),
    ]
