# Generated by Django 4.2.6 on 2023-11-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0009_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='title',
            new_name='ctitle',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='content',
            new_name='story',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_chapters', to='realsite.book'),
        ),
    ]
