# Generated by Django 5.0.1 on 2024-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rented_books',
            field=models.ManyToManyField(blank=True, related_name='rented_by', to='realsite.book'),
        ),
    ]
