# Generated by Django 5.0.1 on 2024-01-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0013_userprofile_bio_alter_userprofile_rented_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=0),
        ),
    ]
