# Generated by Django 5.0.1 on 2024-01-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0016_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Not Rented', 'Not Rented'), ('Rented', 'Rented')], default='Not Rented', max_length=20),
        ),
    ]
