# Generated by Django 5.0.1 on 2024-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsite', '0017_alter_book_options_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
